version: "4"
services:
  wog-app:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - "8777:8777"
  flask-app:
    build: 
      context: .
    ports:
      - "5000:5000"
    command: python3 MainScores.py

